name: Bug report
description: If you encounter disruptive behaviour, open a bug report.
title: 'Bug report'
body:
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behaviour
      description: Here you can summarise what is going on.
      placeholder: e.g. The CLI ignores my configuration path specification.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Describe what you would expect to happen instead.
      placeholder: e.g. I expected the configuration to be used from my --path argument.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Providing a set of concise steps that deterministically reproduce the behaviour helps us investigate what is going on.
      placeholder: |
        For example:
        1. I built the application.
        2. I ran the application via ./cli --path=my-config.yaml
        3. The script returned irrelevant results.
    validations:
      required: true
  - type: input
    id: working-version
    attributes:
      label: Has this worked for you before?
      description: Provide the last working version.
      placeholder: e.g. 1.5.0
    validations:
      required: false
  - type: input
    id: app-version
    attributes:
      label: Used version
      description: What version are you running?
      placeholder: e.g. 1.7.3
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Which operation system are you on?
      options:
        - Linux
        - Windows
        - MacOS
        - other (specify in Additional information)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additonal information is appreciated as it will help with investigating the issue.
      placeholder: e.g. Screenshots, videos, links to minimal reproducible example.
